### ISSUE TITLE
tax tool cannot compile 

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [ncbi/ngs-tools#10]
I know this is not released yet, but it would be nice to try it out and the online instuctions to install do not work:

git clone https://github.com/ncbi/ngs-tools.git --branch tax
cd ./ngs-tools/tools/tax
make Makefile
and in ./examples folder you can find helper *.sh scripts

$make Makefile
/bin/ngs-tools/build/Makefile.shell:27: *** "*** File '/bin/ngs-tools/build/Makefile.config' is missing. Please run /bin/ngs-tools/build/configure".  Stop.

/bin/ngs-tools/build/configure: No such file or directory

**Comment by theo-allnutt-bioinformatics** [comment]
Version 2.7

**Comment by mjoppich** [comment]
I guess the information given on the NCBI website are outdated.

Follow the instruction in issue 3 ( https://github.com/ncbi/ngs-tools/issues/3#issuecomment-288757534 ) and it'll build :)

**Comment by klymenko** [comment]
@theo-allnutt-bioinformatics, do you still need help?
