### ISSUE TITLE
configure finds ncbi-vdb libraries, but not includes

### ISSUE THREAD

**Issue by alanorth** [ncbi/ngs-tools#20]
I'm installing ngs-tools 3.0.0 on a shared cluster environment where applications live on a network-mounted directory. I have compiled and installed ncbi-vdb 3.0.0 successfully and specified the location to `configure` using the `--with-ncbi-vdb-build` option:

```console
$ ./configure --with-ncbi-vdb-build=/export/apps/ncbi-vdb/3.0.0 --prefix=/export/apps/ngs-tools/3.0.0 --debug
...
checking for ncbi-vdb package...        libraries... 
                checking /export/apps/ncbi-vdb/3.0.0/linux/gcc/x86_64/rel/lib/libncbi-vdb.a
                checking /export/apps/ncbi-vdb/3.0.0/lib64/libncbi-vdb.a
        /export/apps/ncbi-vdb/3.0.0/lib64
                not found ../ncbi-vdb
                not found /usr/local/ncbi/ncbi-vdb
                not found /home/aorth/ncbi/ncbi-vdb
no
                ncbi-vdb: includes: ; libs: /export/apps/ncbi-vdb/3.0.0/lib64; ilibs: not needed
configure: error: required ncbi-vdb package not found.
```

Why does the configure script look for the ncbi-vdb includes in a different location than the libs? The libs and includes were installed in the same place by ncbi-vdb's own install script:

```console
$ ls -l /export/apps/ncbi-vdb/3.0.0/
total 8
drwxrwxr-x. 34 aorth aorth 4096 Mar 17 15:26 include/
drwxrwxr-x.  3 aorth aorth 4096 Mar 17 15:25 lib64/
```

I can edit `setup/package.prl` to look for the includes in the correct location for this system... but I'm wondering why?

**Comment by aboshkin** [comment]
Try adding `--with-ncbi-vdb-sources=/export/apps/ncbi-vdb/3.0.0/` to the `./configure` command.

**Comment by alanorth** [comment]
@aboshkin ah, yes that works. I wasn't sure what that option was for—to me it seemed like it wanted the source directory so it could build ncbi-vdb from source during make. With most configure scripts I'm used to passing some option like `--with-ncbi-vdb=` that points to the prefix where such thing is installed, and under the prefix you have lib, include, bin, etc.

Anyways, thanks!

**Comment by alanorth** [comment]
No problem, @aboshkin. Happy to report issues for software I use. It's the last I can do. Also, for what it's worth, I was just building sra-tools and I see they do have `--with-ncbi-vdb-prefix=`! So that's something.
