### ISSUE TITLE
Any recomendation for the two WINDOW parameters? for tools/tax (STAT)

### ISSUE THREAD

**Issue by pmjklemm** [ncbi/ngs-tools#26]
I did download parts of the RefSeq DB (e.g. refseq/fungi) and now I want to build the STAT DB (tools/tax) as described in "examples/". 
I am a bit lost when specifying the hyperparameters DENSE_ and SPARSE_WINDOW. From the paper, I think a KMER_LEN=32 should be optimal but the WINDOW parameters are not described (or I missed it). 

```
KMER_LEN=32;
DENSE_WINDOW=4;
SPARSE_WINDOW=128; 
```

The examples files are all virus genomes, so these values probably are not correct for invertebrates or fungi. 
How do I find out what to use, do you have any hints? 
I know that SRA (within the run-browser) offers this service and parses any dataset but I don't know what parameters are used.

**Comment by multikengineer** [comment]
In the paper under methods you will find: 
_A dense database selects one k-mer per 64 bp segment (“tree_filter”), of input sequence, while a sparse database (“tree_index”) selects one k-mer per 64 bp (Virus), 8000 bp (Eukaryota), and 2000 bp (Bacteria, and Archaea) segment respectfully, noting that segment size is roughly proportional to genome size._  
In the file `build_db_and_run.sh` those two variables are defined for ease. A window is the sliced region (in bp)  from which one MinHash selected Kmer will be selected . In our typical production builds we use a window == 64 for dense db,  and as you can see above three different values for sparse dbs depending on the kingdom.

**Comment by pmjklemm** [comment]
thank you
