### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by ngiangre** [ncbi/ngs-tools#3]
Once I clone the repo, how do I install from there?

**Comment by aboshkin** [comment]
Currently, the way to build/install is:



(assuming you are in the ngs-tools directory, ngs and ncbi-vdb are cloned at the same level as ngs-tools, i.e. the parent directory has 3 subdirs, ngs, ncbi-vdb and ngs-tools)



./configure  --prefix=<dir to install to>         # add --with-debug for debug version

cd build/cmake

./makerelease.sh                                         # or ./makedebug.sh if debug

cd Release

make all install



We are currently working on simplifying the build procedure for this repo; the plan is to have "./configure && make install" work out of the box.



________________________________

**Comment by kwrodarmer** [comment]
@ngiangre - did that address your question?

**Comment by ngiangre** [comment]
I'm in a hackathon with bun busby downstairs right now but I'll get back to this issue within a day. Sorry!

**Comment by ngiangre** [comment]
I am configuring within ngs-tools but it can't locate ngs-sdk which is ../ngs/ngs-sdk and not within ngs-tools

**Comment by kwrodarmer** [comment]
try putting ngs, ncbi-vdb and ngs-tools all at the same level (and for that matter, sra-tools). That's the most common arrangement. Remember the configure steps.

**Comment by ngiangre** [comment]
Yes I have ngs, ngs-tools, ncbi-vdb and sra-tools all at the same level and I'm trying to configure once I'm in ngs-tools, but when it checks for the ngs-sdk package it can't find it. It's in ../ngs/ but the configuration fails.

**Comment by aboshkin** [comment]
Can you post the output of the ./configure command (in ngs-tools)?



________________________________

**Comment by ngiangre** [comment]
Nicholass-MacBook-Pro-2:ngs-tools nickgiangreco$ ./configure --with-debug
Configuring NGS-TOOLS package
checking system type... Darwin
checking machine architecture... x86_64
build architecture: x86_64
checking for supported architecture... x86_64 (64 bits) is supported
checking for supported OS... Darwin (mac) is supported
checking for supported tool chain... clang tool chain is supported
checking for clang++... yes
checking for ngs-sdk package...
	includes... ../ngs/ngs-sdk
configure: error: required ngs-sdk package not found.

**Comment by klymenko** [comment]
Here is the correct sequence of commands:

mksir ~/SRC
cd ~/SRC
git clone https://github.com/ncbi/ngs.git
git clone https://github.com/ncbi/ncbi-vdb.git
git clone https://github.com/ncbi/ngs-tools.git
cd ngs/ngs-sdk
./configure -p=~/NCBI && make
cd ../../ncbi-vdb
./configure -p=~/NCBI && make
cd ../ngs-tools
./configure -p=~/NCBI

**Comment by kwrodarmer** [comment]
He can also run the first configure within `ngs` itself, rather than `ngs/ngs-sdk`, right?

**Comment by klymenko** [comment]
> He can also run the first configure within ngs itself, rather than ngs/ngs-sdk, right?

Yes he can - if he has java and python installed.

**Comment by kwrodarmer** [comment]
Yes, @ngiangre - you're writing Python code, correct?

**Comment by aboshkin** [comment]
Yes. ./configure from ngs/ will also configure Java and Python.



________________________________

**Comment by ngiangre** [comment]
Thank you @klymenko, that worked. I will be writing python code. I'm trying to get count data for ChIPSeq experiments in HEK293 cells. And I have genomic windows in a bed file-can I convert that into a gtf file to use spark_genes tools or can I use the bed file directly?

**Comment by kwrodarmer** [comment]
We have no built-in support for bed files. Ben may have some feedback for you.

**Comment by ngiangre** [comment]
Alright, no worries. I’m sure there’s a bed to gtf conversion tool.

**Comment by ngiangre** [comment]
Thanks for all your help! I'll open a new issue if I have a problem.

**Comment by nroak** [comment]
Can you please put these instructions on the homepage, Readme.md?

> 

Here is the correct sequence of commands:

mkdir \~/SRC ; cd \~/SRC
git clone https://github.com/ncbi/ngs.git
git clone https://github.com/ncbi/ncbi-vdb.git
git clone https://github.com/ncbi/ngs-tools.git
cd ngs/ngs-sdk ; ./configure -p=\~/NCBI && make
cd ../../ncbi-vdb ; ./configure -p=\~/NCBI && make
cd ../ngs-tools ; ./configure -p=\~/NCBI

**Comment by ngiangre** [comment]
@nroak, I made a pull request. Thank you for your comment! This is extremely useful for easier adoption by other users.

**Comment by tardigradus** [comment]
It's 2021 and the correct build instructions still haven't made it into the README.de :-(
