### ISSUE TITLE
Taxonomy analysis on SRA submission inconsistent

### ISSUE THREAD

**Issue by plbergsa** [ncbi/ngs-tools#30]
Case Information:
Case #: CAS-1078261-J6B3G5
Customer Name: Bergsagel, Leif, M.D.
Customer Email: [Bergsagel.leif@mayo.edu](mailto:Bergsagel.leif@mayo.edu)
Case Created: 3/12/2023, 3:33:05 AM

Summary: PRJNA938752

Details:
I have had a problem with Taxonomy analysis of murine samples I have submitted to SRA. I submitted multiple RNAseq, wxs and low pass mate-pair WGS aligned to GRCm39, which were all correctly identified as mus musculus. However, all of the regular WGS files were not identified as mus musculus, with no predominant organisms Identified. Independently I discovered that one of the samples (SRR23619415) contained a sequence from human chrY, and in fact the taxonomy analysis correctly identified 0.32% homo sapiens in that sample, but did not identify the predominant mus musculus sequences. Can you help correct this?

Wgs                      https://dataview.ncbi.nlm.nih.gov/object/SRR23619373 0.08% mus caroli
wgs                       https://dataview.ncbi.nlm.nih.gov/object/SRR23619415 0.32% homo sapiens
 
mate-pair             https://dataview.ncbi.nlm.nih.gov/object/SRR23619250 70.62% mus musculus
wxs                       https://dataview.ncbi.nlm.nih.gov/object/SRR23619426 71.95% mus musculus
RNAseq                https://dataview.ncbi.nlm.nih.gov/object/SRR23619404 55.01% mus musculus

Response from NLM
From: NLM Support <nlm-support@nlm.nih.gov>
Date: Tuesday, March 14, 2023 at 9:46 AM
To: Bergsagel, Leif, M.D. <bergsagel.leif@mayo.edu>
Subject: [EXTERNAL] Re: case #CAS-1078261-J6B3G5: PRJNA938752 TRACKING:000414000018578
We cannot fix taxonomy analysis produced by software. 
Perhaps you sample was contaminated?

**Comment by lapointr** [comment]
The taxonomy analysis table on the data view page is not the best interpretation of the results of STAT for your sequences and SRA is planning to update this display sometime in the future. The values displayed here are not for the most commonly assigned taxa, which is misleading because STAT calculates the distribution of reads identified at all taxonomy classes. When multiple tax nodes are mapped for single spot, STAT uses the lowest non-ambiguous mapping. 

While STAT is not able to assign reads to Mus musculus for SRR23619373 and SRR23619415, the analysis does match around 60% of the reads in each of these sequences to kmers specific to the genus Mus. While these reads are not confidently assigned to Mus musculus they were instead assigned to the taxonomic node directly above it. This distinction will be displayed better when the SRA Runs becomes public. The SRA Run pages for these accessions will provide a more detailed breakdown of the analysis when the Runs become public, and Google BigQuery and Amazon Athena can be used to search the STAT results for even finer detail. 

Should the SRR23619415 human sequences be removed from your Run before your data is released? The SRA can scrub human contaminant sequences from your PRJNA938752 submission by request.

**Comment by plbergsa** [comment]
Thanks for the explanation. I was afraid I may have done something incorrect in submitting the wgs. How do I submit a request to SRA to scrub the human contaminant sequences? I think that would be a good idea.

From: lapointr ***@***.***>
Date: Tuesday, March 14, 2023 at 2:10 PM
To: ncbi/ngs-tools ***@***.***>
Cc: Bergsagel, Leif, M.D. ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [ncbi/ngs-tools] Taxonomy analysis on SRA submission inconsistent (Issue #30)

The taxonomy analysis table on the data view page is not the best interpretation of the results of STAT for your sequences and SRA is planning to update this display sometime in the future. The values displayed here are not for the most commonly assigned taxa, which is misleading because STAT calculates the distribution of reads identified at all taxonomy classes. When multiple tax nodes are mapped for single spot, STAT uses the lowest non-ambiguous mapping.

While STAT is not able to assign reads to Mus musculus for SRR23619373 and SRR23619415, the analysis does match around 60% of the reads in each of these sequences to kmers specific to the genus Mus. While these reads are not confidently assigned to Mus musculus they were instead assigned to the taxonomic node directly above it. This distinction will be displayed better when the SRA Runs becomes public. The SRA Run pages for these accessions will provide a more detailed breakdown of the analysis when the Runs become public, and Google BigQuery and Amazon Athena can be used to search the STAT results for even finer detail.

Should the SRR23619415 human sequences be removed from your Run before your data is released? The SRA can scrub human contaminant sequences from your PRJNA938752 submission by request.

**Comment by plbergsa** [comment]
On second thought, probably best not to scrub the human sequences. These mice contain human transgenes (MYC, CRBN, FGFR3). It would be a big mistake to remove these sequences.

From: lapointr ***@***.***>
Date: Tuesday, March 14, 2023 at 2:10 PM
To: ncbi/ngs-tools ***@***.***>
Cc: Bergsagel, Leif, M.D. ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [ncbi/ngs-tools] Taxonomy analysis on SRA submission inconsistent (Issue #30)

The taxonomy analysis table on the data view page is not the best interpretation of the results of STAT for your sequences and SRA is planning to update this display sometime in the future. The values displayed here are not for the most commonly assigned taxa, which is misleading because STAT calculates the distribution of reads identified at all taxonomy classes. When multiple tax nodes are mapped for single spot, STAT uses the lowest non-ambiguous mapping.

While STAT is not able to assign reads to Mus musculus for SRR23619373 and SRR23619415, the analysis does match around 60% of the reads in each of these sequences to kmers specific to the genus Mus. While these reads are not confidently assigned to Mus musculus they were instead assigned to the taxonomic node directly above it. This distinction will be displayed better when the SRA Runs becomes public. The SRA Run pages for these accessions will provide a more detailed breakdown of the analysis when the Runs become public, and Google BigQuery and Amazon Athena can be used to search the STAT results for even finer detail.

Should the SRR23619415 human sequences be removed from your Run before your data is released? The SRA can scrub human contaminant sequences from your PRJNA938752 submission by request.
